### PR TITLE
Implement Rate Limits

### PR DESCRIPTION
**Pull request by KartikJain14**
Some bonus stuff too ofc.
Implement download and upload rate limit.
Fix a bug where URLs are dynamic and don't really require .env
Change in sitemap.xml

### CODE REVIEW

**Comment by nnisarggada** [comment]
- `URL=request.base_url[:-1]` isn't needed anywhere
- Rate limits to be changed to 5 per minute for upload and 10 per minute for download

**Comment by KartikJain14** [comment]
Done!

**Comment by nnisarggada** [comment]
- Default rate limits to be changed to sometime saner (10 per minute?)
- Add unit of time after `{expiry}` in the email text

**Comment by nnisarggada** [comment]
LGTM!

**Pull request merged**
